"""Dictionnaire de correspondance ECO - nom d'ouverture."""

ECO_OPENINGS = {
    # Volume A - Ouvertures de flanc
    "A00": "Ouverture irrégulière",
    "A01": "Ouverture Larsen",
    "A02": "Ouverture Bird",
    "A03": "Ouverture Bird",
    "A04": "Ouverture Zukertort-Réti",
    "A05": "Ouverture Zukertort-Réti",
    "A06": "Ouverture Zukertort-Réti",
    "A07": "Ouverture Zukertort-Réti",
    "A08": "Ouverture Zukertort-Réti",
    "A09": "Gambit Réti",
    "A10": "Anglaise",
    "A11": "Anglaise, système Caro-Kann",
    "A12": "Anglaise, système Caro-Kann",
    "A13": "Anglaise avec ... e6",
    "A14": "Anglaise avec ... e6",
    "A15": "Anglaise : Défense anglo-indienne",
    "A16": "Anglaise : Défense anglo-indienne",
    "A17": "Anglaise : Défense anglo-indienne",
    "A18": "Anglaise : Défense anglo-indienne",
    "A19": "Anglaise : Défense anglo-indienne",
    "A20": "Anglaise : Ouverture sicilienne inversée",
    "A21": "Anglaise : Ouverture sicilienne inversée",
    "A22": "Anglaise : Ouverture sicilienne inversée",
    "A23": "Anglaise : Ouverture sicilienne inversée",
    "A24": "Anglaise : Ouverture sicilienne inversée",
    "A25": "Anglaise : Ouverture sicilienne inversée",
    "A26": "Anglaise : Ouverture sicilienne inversée",
    "A27": "Anglaise : Ouverture sicilienne inversée",
    "A28": "Anglaise : Ouverture sicilienne inversée",
    "A29": "Anglaise : Ouverture sicilienne inversée",
    "A30": "Anglaise : Ouverture anglaise symétrique",
    "A31": "Anglaise : Ouverture anglaise symétrique",
    "A32": "Anglaise : Ouverture anglaise symétrique",
    "A33": "Anglaise : Ouverture anglaise symétrique",
    "A34": "Anglaise : Ouverture anglaise symétrique",
    "A35": "Anglaise : Ouverture anglaise symétrique",
    "A36": "Anglaise : Ouverture anglaise symétrique",
    "A37": "Anglaise : Ouverture anglaise symétrique",
    "A38": "Anglaise : Ouverture anglaise symétrique",
    "A39": "Anglaise : Ouverture anglaise symétrique",
    "A40": "Ouverture du pion dame",
    "A41": "Défense indienne ancienne",
    "A42": "Défense indienne ancienne",
    "A43": "Défense Benoni ancienne",
    "A44": "Défense Benoni ancienne",
    "A45": "Attaque Trompowsky",
    "A46": "Attaque Torre",
    "A47": "Défense pseudo-ouest-indienne",
    "A48": "Défense est-indienne sans c4",
    "A49": "Défense est-indienne sans c4",
    "A50": "Défense mexicaine",
    "A51": "Gambit de Budapest",
    "A52": "Gambit de Budapest",
    "A53": "Défense vieille-indienne",
    "A54": "Défense vieille-indienne",
    "A55": "Défense vieille-indienne",
    "A56": "Défense Benoni fermée",
    "A57": "Gambit Benko",
    "A58": "Gambit Benko",
    "A59": "Gambit Benko",
    "A60": "Défense Benoni moderne",
    "A61": "Défense Benoni moderne",
    "A62": "Défense Benoni moderne",
    "A63": "Défense Benoni moderne",
    "A64": "Défense Benoni moderne",
    "A65": "Défense Benoni moderne",
    "A66": "Défense Benoni moderne",
    "A67": "Défense Benoni moderne",
    "A68": "Défense Benoni moderne",
    "A69": "Défense Benoni moderne",
    "A70": "Défense Benoni moderne",
    "A71": "Défense Benoni moderne",
    "A72": "Défense Benoni moderne",
    "A73": "Défense Benoni moderne",
    "A74": "Défense Benoni moderne",
    "A75": "Défense Benoni moderne",
    "A76": "Défense Benoni moderne",
    "A77": "Défense Benoni moderne",
    "A78": "Défense Benoni moderne",
    "A79": "Défense Benoni moderne",
    "A80": "Défense hollandaise",
    "A81": "Défense hollandaise : Variante Steinitz-Rubinstein",
    "A82": "Défense hollandaise : Gambit Staunton",
    "A83": "Défense hollandaise : Gambit Staunton",
    "A84": "Défense hollandaise",
    "A85": "Défense hollandaise",
    "A86": "Défense hollandaise : Système de Leningrad",
    "A87": "Défense hollandaise : Système de Leningrad",
    "A88": "Défense hollandaise : Système de Leningrad",
    "A89": "Défense hollandaise : Système de Leningrad",
    "A90": "Défense hollandaise : Système classique",
    "A91": "Défense hollandaise : Système classique",
    "A92": "Défense hollandaise : Variante Alekhine",
    "A93": "Défense hollandaise : Système stonewall classique",
    "A94": "Défense hollandaise : Système stonewall classique",
    "A95": "Défense hollandaise : Système stonewall classique",
    "A96": "Défense hollandaise : Variante Iline Jenevski",
    "A97": "Défense hollandaise : Variante Iline Jenevski",
    "A98": "Défense hollandaise : Variante Iline Jenevski",
    "A99": "Défense hollandaise : Variante Iline Jenevski",

    # Volume B - Débuts semi-ouverts
    "B00": "Défense Nimzowitsch du pion roi",
    "B01": "Défense scandinave",
    "B02": "Défense Alekhine",
    "B03": "Défense Alekhine",
    "B04": "Défense Alekhine",
    "B05": "Défense Alekhine",
    "B06": "Défense Robatsch",
    "B07": "Défense Pirc",
    "B08": "Défense Pirc",
    "B09": "Défense Pirc",
    "B10": "Défense Caro-Kann",
    "B11": "Défense Caro-Kann",
    "B12": "Défense Caro-Kann : Variante d'avance",
    "B13": "Défense Caro-Kann : Variante d'échange",
    "B14": "Défense Caro-Kann : Attaque Panov",
    "B15": "Défense Caro-Kann : Variante ouverte",
    "B16": "Défense Caro-Kann : Variante ouverte",
    "B17": "Défense Caro-Kann : Variante ouverte",
    "B18": "Défense Caro-Kann : Variante ouverte",
    "B19": "Défense Caro-Kann : Variante ouverte",
    "B20": "Défense sicilienne : Gambit Morra",
    "B21": "Défense sicilienne : Attaque grand prix",
    "B22": "Défense sicilienne : Variante Alapine",
    "B23": "Sicilienne fermée",
    "B24": "Sicilienne fermée",
    "B25": "Sicilienne fermée",
    "B26": "Sicilienne fermée",
    "B27": "Défense sicilienne",
    "B28": "Défense sicilienne : Variante O'Kelly",
    "B29": "Défense sicilienne : Variante Nimzowitsch",
    "B30": "Défense sicilienne : Attaque Rossolimo",
    "B31": "Défense sicilienne : Attaque Rossolimo",
    "B32": "Défense sicilienne : Variante du dragon accéléré",
    "B33": "Défense sicilienne : Variante Svechnikov",
    "B34": "Défense sicilienne : Variante du dragon accéléré",
    "B35": "Défense sicilienne : Variante du dragon accéléré",
    "B36": "Défense sicilienne : Variante du dragon accéléré",
    "B37": "Défense sicilienne : Variante du dragon accéléré",
    "B38": "Défense sicilienne : Variante du dragon accéléré",
    "B39": "Défense sicilienne : Variante du dragon accéléré",
    "B40": "Défense sicilienne : Variante Paulsen",
    "B41": "Défense sicilienne : Variante Kan",
    "B42": "Défense sicilienne : Variante Kan",
    "B43": "Défense sicilienne : Variante Kan",
    "B44": "Défense sicilienne : Variante Paulsen",
    "B45": "Défense sicilienne : Sicilienne des quatre cavaliers",
    "B46": "Défense sicilienne : Variante Taïmanov",
    "B47": "Défense sicilienne : Variante Taïmanov",
    "B48": "Défense sicilienne : Variante Taïmanov",
    "B49": "Défense sicilienne : Variante Taïmanov",
    "B50": "Défense sicilienne : 1.e4 c5 ; 2.Cf3 d6",
    "B51": "Défense sicilienne : Variante de Moscou",
    "B52": "Défense sicilienne : Variante de Moscou",
    "B53": "Défense sicilienne : Variante Tchekhover",
    "B54": "Défense sicilienne",
    "B55": "Défense sicilienne : Variante anti-dragon",
    "B56": "Défense sicilienne : Variante classique",
    "B57": "Défense sicilienne : Variante classique",
    "B58": "Défense sicilienne : Variante classique",
    "B59": "Défense sicilienne : Variante classique",
    "B60": "Défense sicilienne : Variante classique",
    "B61": "Défense sicilienne : Variante classique",
    "B62": "Défense sicilienne : Variante classique",
    "B63": "Défense sicilienne : Variante classique",
    "B64": "Défense sicilienne : Variante classique",
    "B65": "Défense sicilienne : Variante classique",
    "B66": "Défense sicilienne : Variante classique",
    "B67": "Défense sicilienne : Variante classique",
    "B68": "Défense sicilienne : Variante classique",
    "B69": "Défense sicilienne : Variante classique",
    "B70": "Défense sicilienne : Variante du dragon",
    "B71": "Défense sicilienne : Variante du dragon",
    "B72": "Défense sicilienne : Variante du dragon",
    "B73": "Défense sicilienne : Variante du dragon",
    "B74": "Défense sicilienne : Variante du dragon",
    "B75": "Défense sicilienne : Variante du dragon",
    "B76": "Défense sicilienne : Variante du dragon",
    "B77": "Défense sicilienne : Variante du dragon",
    "B78": "Défense sicilienne : Variante du dragon",
    "B79": "Défense sicilienne : Variante du dragon",
    "B80": "Défense sicilienne : Variante de Scheveningue",
    "B81": "Défense sicilienne : Variante de Scheveningue",
    "B82": "Défense sicilienne : Variante de Scheveningue",
    "B83": "Défense sicilienne : Variante de Scheveningue",
    "B84": "Défense sicilienne : Variante de Scheveningue",
    "B85": "Défense sicilienne : Variante de Scheveningue",
    "B86": "Défense sicilienne : Variante de Scheveningue",
    "B87": "Défense sicilienne : Variante de Scheveningue",
    "B88": "Défense sicilienne : Variante de Scheveningue",
    "B89": "Défense sicilienne : Variante de Scheveningue",
    "B90": "Défense sicilienne : Variante Najdorf",
    "B91": "Défense sicilienne : Variante Najdorf",
    "B92": "Défense sicilienne : Variante Najdorf",
    "B93": "Défense sicilienne : Variante Najdorf",
    "B94": "Défense sicilienne : Variante Najdorf",
    "B95": "Défense sicilienne : Variante Najdorf",
    "B96": "Défense sicilienne : Variante Najdorf",
    "B97": "Défense sicilienne : Variante Najdorf",
    "B98": "Défense sicilienne : Variante Najdorf",
    "B99": "Défense sicilienne : Variante Najdorf",

    # Volume C - Débuts ouverts
    "C00": "Française : Défense française",
    "C01": "Française",
    "C02": "Française : Variante d'avance",
    "C03": "Française : Variante Tarrasch",
    "C04": "Française : Variante Tarrasch",
    "C05": "Française : Variante Tarrasch",
    "C06": "Française : Variante Tarrasch",
    "C07": "Française : Variante Tarrasch",
    "C08": "Française : Variante Tarrasch",
    "C09": "Française : Variante Tarrasch",
    "C10": "Française",
    "C11": "Française : Variante classique",
    "C12": "Française : Variante classique",
    "C13": "Française : Variante classique",
    "C14": "Française : Variante classique",
    "C15": "Française : Variante Winawer",
    "C16": "Française : Variante Winawer",
    "C17": "Française : Variante Winawer",
    "C18": "Française : Variante Winawer",
    "C19": "Française : Variante Winawer",
    "C20": "Début ouvert",
    "C21": "Partie du centre",
    "C22": "Partie du centre",
    "C23": "Partie du fou",
    "C24": "Partie du fou",
    "C25": "Partie viennoise",
    "C26": "Partie viennoise",
    "C27": "Partie viennoise",
    "C28": "Partie viennoise",
    "C29": "Partie viennoise",
    "C30": "Gambit du roi",
    "C31": "Gambit du roi",
    "C32": "Gambit du roi",
    "C33": "Gambit du roi",
    "C34": "Gambit du roi",
    "C35": "Gambit du roi",
    "C36": "Gambit du roi",
    "C37": "Gambit du roi",
    "C38": "Gambit du roi",
    "C39": "Gambit du roi",
    "C40": "Gambit letton",
    "C41": "Défense Philidor",
    "C42": "Défense russe (Petrov)",
    "C43": "Défense russe (Petrov)",
    "C44": "Début Ponziani",
    "C45": "Partie écossaise",
    "C46": "Partie des trois cavaliers",
    "C47": "Partie des quatre cavaliers",
    "C48": "Partie des quatre cavaliers",
    "C49": "Partie des quatre cavaliers",
    "C50": "Partie italienne",
    "C51": "Partie italienne",
    "C52": "Partie italienne",
    "C53": "Partie italienne",
    "C54": "Partie italienne",
    "C55": "Défense des deux cavaliers",
    "C56": "Défense des deux cavaliers",
    "C57": "Défense des deux cavaliers",
    "C58": "Défense des deux cavaliers",
    "C59": "Défense des deux cavaliers",
    "C60": "Espagnole",
    "C61": "Espagnole : Défense Bird",
    "C62": "Espagnole : Défense Steinitz",
    "C63": "Espagnole : Gambit Jaenisch",
    "C64": "Espagnole : Défense classique",
    "C65": "Espagnole : Défense berlinoise",
    "C66": "Espagnole : Défense berlinoise",
    "C67": "Espagnole : Défense berlinoise",
    "C68": "Espagnole : Variante d'échange",
    "C69": "Espagnole : Variante d'échange",
    "C70": "Espagnole : Variante Steinitz différée",
    "C71": "Espagnole : Variante Steinitz différée",
    "C72": "Espagnole : Variante Steinitz différée",
    "C73": "Espagnole : Variante Steinitz différée",
    "C74": "Espagnole : Variante Steinitz différée",
    "C75": "Espagnole : Variante Steinitz différée",
    "C76": "Espagnole : Variante Steinitz différée",
    "C77": "Espagnole",
    "C78": "Espagnole",
    "C79": "Espagnole : Variante Rubinstein",
    "C80": "Espagnole : Variante ouverte",
    "C81": "Espagnole : Variante ouverte",
    "C82": "Espagnole : Variante ouverte",
    "C83": "Espagnole : Variante ouverte",
    "C84": "Espagnole",
    "C85": "Espagnole : Variante d'échange différée",
    "C86": "Espagnole : Attaque Worrall",
    "C87": "Espagnole",
    "C88": "Espagnole : Variantes anti-Marshall",
    "C89": "Espagnole : Gambit Marshall",
    "C90": "Espagnole : Système fermé",
    "C91": "Espagnole : Variante Yates",
    "C92": "Espagnole : Variantes Flohr-Zaïtsev",
    "C93": "Espagnole : Variante Smyslov",
    "C94": "Espagnole : Variante Breyer",
    "C95": "Espagnole : Variante Breyer",
    "C96": "Espagnole : Variante Tchigorine",
    "C97": "Espagnole : Variante Tchigorine",
    "C98": "Espagnole : Variante Tchigorine",
    "C99": "Espagnole : Variante Tchigorine",

    # Volume D - Débuts fermés
    "D00": "Système Stonewall",
    "D01": "Attaque Richter-Veressov",
    "D02": "Système de Londres",
    "D03": "Variante Tartakover",
    "D04": "Système Colle",
    "D05": "Système Colle",
    "D06": "Gambit dame",
    "D07": "Gambit dame : Défense Tchigorine",
    "D08": "Gambit dame : Contre-gambit Albin",
    "D09": "Gambit dame : Contre-gambit Albin",
    "D10": "Gambit dame : Défense slave",
    "D11": "Gambit dame : Défense slave",
    "D12": "Gambit dame : Défense slave",
    "D13": "Gambit dame : Défense slave",
    "D14": "Gambit dame : Défense slave",
    "D15": "Gambit dame : Défense slave",
    "D16": "Gambit dame : Défense slave",
    "D17": "Gambit dame : Défense slave",
    "D18": "Gambit dame : Défense slave",
    "D19": "Gambit dame : Défense slave",
    "D20": "Gambit dame : Accepté",
    "D21": "Gambit dame : Accepté",
    "D22": "Gambit dame : Accepté",
    "D23": "Gambit dame : Accepté",
    "D24": "Gambit dame : Accepté",
    "D25": "Gambit dame : Accepté",
    "D26": "Gambit dame : Accepté",
    "D27": "Gambit dame : Accepté",
    "D28": "Gambit dame : Accepté",
    "D29": "Gambit dame : Accepté",
    "D30": "Gambit dame : Refusé",
    "D31": "Gambit dame refusé : Défense semi-slave accélérée",
    "D32": "Gambit dame refusé : Défense Tarrasch",
    "D33": "Gambit dame refusé : Défense Tarrasch",
    "D34": "Gambit dame refusé : Défense Tarrasch",
    "D35": "Gambit dame refusé : Variante d'échange",
    "D36": "Gambit dame refusé : Variante d'échange",
    "D37": "Gambit dame refusé",
    "D38": "Gambit dame refusé : Défense Ragozine",
    "D39": "Gambit dame refusé : Défense Ragozine",
    "D40": "Gambit dame refusé : Défense semi-Tarrasch",
    "D41": "Gambit dame refusé : Défense semi-Tarrasch",
    "D42": "Gambit dame refusé : Défense semi-Tarrasch",
    "D43": "Gambit dame refusé : Défense semi-slave",
    "D44": "Gambit dame refusé : Défense semi-slave",
    "D45": "Gambit dame refusé : Défense semi-slave",
    "D46": "Gambit dame refusé : Défense semi-slave",
    "D47": "Gambit dame refusé : Défense semi-slave",
    "D48": "Gambit dame refusé : Défense semi-slave",
    "D49": "Gambit dame refusé : Défense semi-slave",
    "D50": "Gambit dame refusé : Variante hollandaise",
    "D51": "Gambit dame refusé : Défense Cambridge-Springs",
    "D52": "Gambit dame refusé : Défense Cambridge-Springs",
    "D53": "Gambit dame refusé : Variante anti-néo-orthodoxe",
    "D54": "Gambit dame refusé : Variante anti-néo-orthodoxe",
    "D55": "Gambit dame refusé",
    "D56": "Gambit dame refusé : Variante Lasker",
    "D57": "Gambit dame refusé : Variante Lasker",
    "D58": "Gambit dame refusé : Variante Tartakover",
    "D59": "Gambit dame refusé : Variante Tartakover",
    "D60": "Gambit dame refusé : Défense orthodoxe",
    "D61": "Gambit dame refusé : Défense orthodoxe",
    "D62": "Gambit dame refusé : Défense orthodoxe",
    "D63": "Gambit dame refusé : Défense orthodoxe",
    "D64": "Gambit dame refusé : Défense orthodoxe",
    "D65": "Gambit dame refusé : Défense orthodoxe",
    "D66": "Gambit dame refusé : Défense orthodoxe",
    "D67": "Gambit dame refusé : Défense orthodoxe",
    "D68": "Gambit dame refusé : Défense orthodoxe",
    "D69": "Gambit dame refusé : Défense orthodoxe",
    "D70": "Défense Grünfeld : Attaque Nimzowitsch",
    "D71": "Défense néo-Grünfeld",
    "D72": "Défense néo-Grünfeld",
    "D73": "Défense néo-Grünfeld",
    "D74": "Défense néo-Grünfeld",
    "D75": "Défense néo-Grünfeld",
    "D76": "Défense néo-Grünfeld",
    "D77": "Défense néo-Grünfeld",
    "D78": "Défense néo-Grünfeld",
    "D79": "Défense néo-Grünfeld",
    "D80": "Défense Grünfeld",
    "D81": "Défense Grünfeld : Variante Botvinnik",
    "D82": "Défense Grünfeld : Système classique",
    "D83": "Défense Grünfeld : Système classique",
    "D84": "Défense Grünfeld : Système classique",
    "D85": "Défense Grünfeld : Variante d'échange",
    "D86": "Défense Grünfeld : Variante d'échange",
    "D87": "Défense Grünfeld : Variante d'échange",
    "D88": "Défense Grünfeld : Variante d'échange",
    "D89": "Défense Grünfeld : Variante d'échange",
    "D90": "Défense Grünfeld",
    "D91": "Défense Grünfeld : Variante Taïmanov",
    "D92": "Défense Grünfeld : Attaque hongroise",
    "D93": "Défense Grünfeld : Attaque hongroise",
    "D94": "Défense Grünfeld : Variante fermée",
    "D95": "Défense Grünfeld : Variante fermée",
    "D96": "Défense Grünfeld : Variante russe",
    "D97": "Défense Grünfeld : Variante russe",
    "D98": "Défense Grünfeld : Variante russe",
    "D99": "Défense Grünfeld : Variante russe",

    # Volume E - Débuts indiens
    "E00": "Catalane : Attaque néo-indienne",
    "E01": "Partie catalane",
    "E02": "Partie catalane",
    "E03": "Partie catalane",
    "E04": "Partie catalane",
    "E05": "Partie catalane",
    "E06": "Partie catalane",
    "E07": "Partie catalane",
    "E08": "Partie catalane",
    "E09": "Partie catalane",
    "E10": "Défense Döry",
    "E11": "Défense Bogo-indienne",
    "E12": "Défense ouest-indienne",
    "E13": "Défense ouest-indienne",
    "E14": "Défense ouest-indienne",
    "E15": "Défense ouest-indienne",
    "E16": "Défense ouest-indienne",
    "E17": "Défense ouest-indienne",
    "E18": "Défense ouest-indienne",
    "E19": "Défense ouest-indienne",
    "E20": "Défense nimzo-indienne",
    "E21": "Défense nimzo-indienne : Variante des trois cavaliers",
    "E22": "Défense nimzo-indienne : Variante Spielmann",
    "E23": "Défense nimzo-indienne : Variante Spielmann",
    "E24": "Défense nimzo-indienne : Variante Sämisch",
    "E25": "Défense nimzo-indienne : Variante Sämisch",
    "E26": "Défense nimzo-indienne : Variante Sämisch",
    "E27": "Défense nimzo-indienne : Variante Sämisch",
    "E28": "Défense nimzo-indienne : Variante Sämisch",
    "E29": "Défense nimzo-indienne : Variante Sämisch",
    "E30": "Défense nimzo-indienne : Variante de Léningrad",
    "E31": "Défense nimzo-indienne : Variante de Léningrad",
    "E32": "Défense nimzo-indienne : Variante classique",
    "E33": "Défense nimzo-indienne : Variante classique",
    "E34": "Défense nimzo-indienne : Variante classique",
    "E35": "Défense nimzo-indienne : Variante classique",
    "E36": "Défense nimzo-indienne : Variante classique",
    "E37": "Défense nimzo-indienne : Variante classique",
    "E38": "Défense nimzo-indienne : Variante classique",
    "E39": "Défense nimzo-indienne : Variante classique",
    "E40": "Défense nimzo-indienne : Variante Rubinstein",
    "E41": "Défense nimzo-indienne : Variante Rubinstein",
    "E42": "Défense nimzo-indienne : Variante Rubinstein",
    "E43": "Défense nimzo-indienne : Variante Rubinstein",
    "E44": "Défense nimzo-indienne : Variante Rubinstein",
    "E45": "Défense nimzo-indienne : Variante Rubinstein",
    "E46": "Défense nimzo-indienne : Variante Rubinstein",
    "E47": "Défense nimzo-indienne : Variante Rubinstein",
    "E48": "Défense nimzo-indienne : Variante Rubinstein",
    "E49": "Défense nimzo-indienne : Variante Rubinstein",
    "E50": "Défense nimzo-indienne : Variante Rubinstein",
    "E51": "Défense nimzo-indienne : Variante Rubinstein",
    "E52": "Défense nimzo-indienne : Variante Rubinstein",
    "E53": "Défense nimzo-indienne : Variante Rubinstein",
    "E54": "Défense nimzo-indienne : Variante Rubinstein",
    "E55": "Défense nimzo-indienne : Variante Rubinstein",
    "E56": "Défense nimzo-indienne : Variante Rubinstein",
    "E57": "Défense nimzo-indienne : Variante Rubinstein",
    "E58": "Défense nimzo-indienne : Variante Rubinstein",
    "E59": "Défense nimzo-indienne : Variante Rubinstein",
    "E60": "Défense est-indienne",
    "E61": "Défense est-indienne",
    "E62": "Défense est-indienne : Variante du fianchetto",
    "E63": "Défense est-indienne : Variante du fianchetto",
    "E64": "Défense est-indienne : Variante du fianchetto",
    "E65": "Défense est-indienne : Variante du fianchetto",
    "E66": "Défense est-indienne : Variante du fianchetto",
    "E67": "Défense est-indienne : Variante du fianchetto",
    "E68": "Défense est-indienne : Variante du fianchetto",
    "E69": "Défense est-indienne : Variante du fianchetto",
    "E70": "Défense est-indienne",
    "E71": "Défense est-indienne : Variante Makogonov",
    "E72": "Défense est-indienne : Variante du fianchetto",
    "E73": "Défense est-indienne : Variante Averbakh",
    "E74": "Défense est-indienne : Variante Averbakh",
    "E75": "Défense est-indienne : Variante Averbakh",
    "E76": "Défense est-indienne : Attaque des quatre pions",
    "E77": "Défense est-indienne : Attaque des quatre pions",
    "E78": "Défense est-indienne : Attaque des quatre pions",
    "E79": "Défense est-indienne : Attaque des quatre pions",
    "E80": "Défense est-indienne : Variante Sämisch",
    "E81": "Défense est-indienne : Variante Sämisch",
    "E82": "Défense est-indienne : Variante Sämisch",
    "E83": "Défense est-indienne : Variante Sämisch",
    "E84": "Défense est-indienne : Variante Sämisch",
    "E85": "Défense est-indienne : Variante Sämisch",
    "E86": "Défense est-indienne : Variante Sämisch",
    "E87": "Défense est-indienne : Variante Sämisch",
    "E88": "Défense est-indienne : Variante Sämisch",
    "E89": "Défense est-indienne : Variante Sämisch",
    "E90": "Défense est-indienne : Variante classique",
    "E91": "Défense est-indienne : Variante classique",
    "E92": "Défense est-indienne : Variante classique",
    "E93": "Défense est-indienne : Variante classique",
    "E94": "Défense est-indienne : Variante classique",
    "E95": "Défense est-indienne : Variante classique",
    "E96": "Défense est-indienne : Variante classique",
    "E97": "Défense est-indienne : Variante classique",
    "E98": "Défense est-indienne : Variante classique",
    "E99": "Défense est-indienne : Variante classique",
}


def get_opening_name(eco_code: str) -> str:
    """Retourne le nom de l'ouverture correspondant au code ECO.
    
    Args:
        eco_code: Code ECO (ex: "C45", "B01", "D02")
        
    Returns:
        Nom de l'ouverture ou le code ECO si non trouvé
    """
    if not eco_code:
        return "Ouverture inconnue"
    
    # Normalisation du code ECO
    eco_code = eco_code.upper().strip()
    
    return ECO_OPENINGS.get(eco_code, eco_code)
